services:
  - type: web
    name: mgt160-mockup
    env: static
    buildCommand: npm install && node build-config.js
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html


